repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      args: [--unsafe]
    - id: debug-statements
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: name-tests-test
      args: [--django]
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [--line-length=120]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
      - id: flake8
        args: [--max-line-length=120]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    - id: mypy
      additional_dependencies: [pydantic==1.6.1]
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest --ignore=tests/integration/ --ignore=tests/resources/ -p no:cacheprovider -p no:warnings -v
      language: python
      'types': [python]
      args: []
      pass_filenames: false
      stages: [commit]
